## Site settings
email: manuel.vargas.alegria@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Philosophy of technology in education. 
description: Today we need reflexions about the transitions process in many differents ways that can be produce a radical change in the manner that teach and learn in our global society. 
url: "https://manuelvarzen.github.io/"
twitter: 
    username: manuelvarzen
    site: https://www.twitter.com/manuelvarzen
    default_img: /img/education_technology.jpg
    lang: es

# Profile settings
name: ManuelVarZen 
profile_img: "/img/Vigia-1.png"  
profile: Manuel Vargas Alegría is an apprentice of philosophy of technology for formal education systems. As such, he works on constructing questions that orient a sense to the tasks of public management as well as private activity.
social: 
    github: "https://github.com/manuelvarzen"
    twitter: "https://twitter.com/manuelvarzen"
    facebook: "https://www.facebook.com/manuelvarzen"
    linkedin: "https://www.linkedin.com/in/manuelvarzen"

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
style: compressed

